[package]
name = "mission-control"
version = "0.1.0"
authors = ["Štěpán Beneš <benes.stepan@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.2.0", features = ["full"] }
tokio-serial = { version = "5.4.1", features = ["rt", "codec"] }
tokio-util = "0.6.9"
bytes = "1.1.0"
futures = "0.3.19"
stick = "0.12.2"
