[package]
name = "mission-control"
version = "0.1.0"
authors = ["Štěpán Beneš <benes.stepan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mio-serial = "3.3.1"
signal-hook = "0.3.6"
gilrs = "0.8.0"
string-error = "0.1.0"
