[package]
name = "mission-control"
version = "0.1.0"
authors = ["Štěpán Beneš <benes.stepan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssl = { version = "0.10", features = ["vendored"] }
mio-serial = "3.3.1"
signal-hook = "0.3.6"
gilrs = "0.8.0"
string-error = "0.1.0"
tungstenite = "0.13.0"
url = "2.2.1"
serde = { version = "1.0.123", features = ["derive"] }
serde_json = "1.0.62"