#!/bin/bash
set -e

PI_IP=192.168.1.60
TARGET=armv7-unknown-linux-gnueabihf

# build binary
cargo build --release --target $TARGET

# upload binary
scp -r ./target/$TARGET/release/mission-control pi@$PI_IP:/home/pi/mission-control/target/release/mission-control

# execute binary
#ssh pi@$PI_IP './mission-control/target/release/mission-control'
